const GET_ALL = 'GET_ALL';
const GET_ALL_DIETS = 'GET_ALL_DIETS';
const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
const CLEAN_DATA = 'CLEAN_DATA';
const FILTER_BY_DIETS = 'FILTER_BY_DIETS';
const ORDER_BY_SCORE = 'ORDER_BY_SCORE';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const RECIPE_DETAIL = 'RECIPE_DETAIL';
const POST_RECIPE = 'POST_RECIPE';
const FILTER_BY_CREATOR = 'FILTER_BY_CREATOR';

module.exports ={
    GET_ALL,
    GET_ALL_DIETS,
    SEARCH_BY_NAME,
    CLEAN_DATA,
    FILTER_BY_CREATOR,
    FILTER_BY_DIETS,
    ORDER_BY_NAME,
    ORDER_BY_SCORE,
    RECIPE_DETAIL,
    POST_RECIPE
}